In [10]:
from models.sos import ScalarOnScalarModel
from optimizers.nbdo import NBDO
import numpy as np

In [2]:
model_sos = ScalarOnScalarModel(Kx=5)

In [3]:
optimizer = NBDO(model=model_sos, latent_dim=2)
optimizer.compute_train_set(num_designs=100, runs=12)

In [4]:
optimizer.fit(epochs=50, patience=10)

/Users/thodorisladas/Documents/code/latent_design_labs/.venv/lib/python3.11/site-packages/keras/src/layers/activations/leaky_relu.py:41: UserWarning: Argument `alpha` is deprecated. Use `negative_slope` instead.
  warnings.warn(


In [5]:
best_criterion, best_design = optimizer.optimize()

Iteration No: 1 started. Evaluating function at random point.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
Iteration No: 1 ended. Evaluation done at random point.
Time taken: 0.0361
Function value obtained: 37.9765
Current minimum: 37.9765
Iteration No: 2 started. Evaluating function at random point.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
Iteration No: 2 ended. Evaluation done at random point.
Time taken: 0.0220
Function value obtained: 13.9841
Current minimum: 13.9841
Iteration No: 3 started. Evaluating function at random point.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
Iteration No: 3 ended. Evaluation done at random point.
Time taken: 0.0232
Function value obtained: 32.2062
Current minimum: 13.9841
Iteration No: 4 started. Evaluating function at random point.
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
Iteration No: 4 ended. Evaluation done at random point.
Time taken: 0.0213
Function value obtained: 12.3620
Current minimum: 12.3620
Iteration No: 5 started. Evaluating function at random point.
1/1 ━━

/Users/thodorisladas/Documents/code/latent_design_labs/.venv/lib/python3.11/site-packages/skopt/optimizer/optimizer.py:517: UserWarning: The objective has been evaluated at point [np.int64(-1), np.int64(1)] before, using random point [np.int64(1), np.int64(0)]
  warnings.warn(


In [6]:
best_criterion

np.float64(1.2341310340300788)

In [11]:
print(np.round(best_design))

[[-1.  1. -0.  0. -1.]
 [-1.  1. -1. -0.  0.]
 [ 1. -1. -1.  1. -0.]
 [ 1.  1.  1. -1.  0.]
 [ 1. -0.  1. -0. -1.]
 [-1. -1.  1.  0. -1.]
 [ 0. -0.  1.  0.  0.]
 [-1.  1.  1.  1.  1.]
 [ 1.  0. -1. -1. -0.]
 [ 0. -0.  1.  1.  1.]
 [-0.  0. -1.  1.  1.]
 [-1. -1.  0. -1.  1.]]
